tickers = {
    "1inch (1INCH)": "1INCH-USD",
    "ACE (ACE)": "ACE-USD",
    "Aave (AAVE)": "AAVE-USD",
    "Algorand (ALGO)": "ALGO-USD",
    "ApeCoin (APE)": "APE-USD",
    "Arbitrum (ARB)": "ARB-USD",
    "Axie Infinity (AXS)": "AXS-USD",
    "Basic Attention Token (BAT)": "BAT-USD",
    "Bitcoin (BTC)": "BTC-USD",
    "Bitcoin Cash (BCH)": "BCH-USD",
    "BNB (BNB)": "BNB-USD",
    "Cardano (ADA)": "ADA-USD",
    "Chiliz (CHZ)": "CHZ-USD",
    "Cronos (CRO)": "CRO-USD",
    "Curve DAO (CRV)": "CRV-USD",
    "Dash (DASH)": "DASH-USD",
    "Decentraland (MANA)": "MANA-USD",
    "Dogecoin (DOGE)": "DOGE-USD",
    "DYDX (DYDX)": "DYDX-USD",
    "EOS (EOS)": "EOS-USD",
    "Ethereum (ETH)": "ETH-USD",
    "Fantom (FTM)": "FTM-USD",
    "Fetch.ai (FET)": "FET-USD",
    "Filecoin (FIL)": "FIL-USD",
    "Flow (FLOW)": "FLOW-USD",
    "Frax (FRAX)": "FRAX-USD",
    "Gala (GALA)": "GALA-USD",
    "Gnosis (GNO)": "GNO-USD",
    "GAS (GAS)": "GAS-USD",
    "Harmony (ONE)": "ONE-USD",
    "Hedera (HBAR)": "HBAR-USD",
    "Helium (HNT)": "HNT-USD",
    "HOOK (HOOK)": "HOOK-USD",
    "Immutable (IMX)": "IMX-USD",
    "Injective (INJ)": "INJ-USD",
    "IOST (IOST)": "IOST-USD",
    "IOTA (IOTA)": "IOTA-USD",
    "Internet Computer (ICP)": "ICP-USD",
    "Kava (KAVA)": "KAVA-USD",
    "Kusama (KSM)": "KSM-USD",
    "Lido DAO (LDO)": "LDO-USD",
    "Litecoin (LTC)": "LTC-USD",
    "Maker (MKR)": "MKR-USD",
    "MANTA (MANTA)": "MANTA-USD",
    "Monero (XMR)": "XMR-USD",
    "MultiversX (EGLD)": "EGLD-USD",
    "NEAR Protocol (NEAR)": "NEAR-USD",
    "Ocean Protocol (OCEAN)": "OCEAN-USD",
    "Optimism (OP)": "OP-USD",
    "PancakeSwap (CAKE)": "CAKE-USD",
    "Pepe (PEPE)": "PEPE-USD",
    "Polygon (MATIC)": "MATIC-USD",
    "Polkadot (DOT)": "DOT-USD",
    "Quant (QNT)": "QNT-USD",
    "QTUM (QTUM)": "QTUM-USD",
    "Ravencoin (RVN)": "RVN-USD",
    "RDNT (RDNT)": "RDNT-USD",
    "Render (RNDR)": "RNDR-USD",
    "Ripple (XRP)": "XRP-USD",
    "SAND (SAND)": "SAND-USD",
    "Shiba Inu (SHIB)": "SHIB-USD",
    "SOL (SOL)": "SOL-USD",
    "Stacks (STX)": "STX-USD",
    "Stellar (XLM)": "XLM-USD",
    "STMX (STMX)": "STMX-USD",
    "STORJ (STORJ)": "STORJ-USD",
    "SUI (SUI)": "SUI-USD",
    "SXP (SXP)": "SXP-USD",
    "Tezos (XTZ)": "XTZ-USD",
    "The Graph (GRT)": "GRT-USD",
    "THETA (THETA)": "THETA-USD",
    "Toncoin (TON)": "TON-USD",
    "TRON (TRX)": "TRX-USD",
    "TrueUSD (TUSD)": "TUSD-USD",
    "Uniswap (UNI)": "UNI-USD",
    "USD Coin (USDC)": "USDC-USD",
    "VeChain (VET)": "VET-USD",
    "WOO Network (WOO)": "WOO-USD",
    "Wrapped Bitcoin (WBTC)": "WBTC-USD",
    "XDC Network (XDC)": "XDC-USD",
    "Zcash (ZEC)": "ZEC-USD",
    "ZIL (ZIL)": "ZIL-USD"
}
